// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace PomeloSoftBlogCaseWebAPI.Models
{
    public partial class PomelosoftblogcasewebapiContext : DbContext
    {
        public PomelosoftblogcasewebapiContext()
        {
        }

        public PomelosoftblogcasewebapiContext(DbContextOptions<PomelosoftblogcasewebapiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TblBlogYazi> TblBlogYazi { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-TVS9I3D\\SQLEXPRESS;Initial Catalog=PomeloSoftBlogCase;Integrated Security=True");
            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<TblBlogYazi>(entity =>
            {
                entity.ToTable("tbl_BlogYazi");

                entity.Property(e => e.Aciklama).IsRequired();

                entity.Property(e => e.Baslik)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Resim).HasColumnType("text");

                entity.Property(e => e.Tarih).HasColumnType("date");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}