// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PomeloSoftBlogCaseWebAPI.Models
{
    public partial class TblBlogYazi
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public int? GirisSayisi { get; set; }
        public DateTime? Tarih { get; set; }
    }
}