// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PomeloSoftBlogCaseMVC.Models
{
    public partial class TblKullanici
    {
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciSoyadi { get; set; }
        public string KullaniciNickName { get; set; }
        public string KullaniciParola { get; set; }
    }
}